psn

diff --git a/rack/mv-qualog b/rack/mv-qualog
--- a/rack/mv-qualog
+++ b/rack/mv-qualog
@@ -1,7 +1,7 @@
 
 hl-smi &>/dev/null
 if [[ $? == 1 ]]; then
-	echo -e "  error: hl driver not loaded"
+	echo -e "  error: hl drivers not loaded"
 	echo -e "  modprobe habanalabs_en &&  modprobe habanalabs_ib &&  modprobe habanalabs_cn &&  modprobe habanalabs"
 	exit 1
 fi
@@ -12,7 +12,12 @@ PSN=$(ipmitool fru | grep "Product Serial" | awk -F': ' '{print $2}')
 SNM=$(ipmitool fru | grep "Board Serial"   | awk -F': ' '{print $2}')
 [[ "$PSN" =~ ^[A-Z[0-9] ]] && SNM=$PSN
 
-tail -n 1  /var/log/habana_logs/qual/*.log | grep -v \= | grep .
+tail -n 1 /var/log/habana_logs/qual/*.log | grep -v \= | grep .
+if [[ $? == 1 ]]; then
+	echo -e "  error: hl_qual logs not found"
+	exit 1
+fi
+
 BID=$(hl-smi -L | grep accel0 | awk -F':' '{print $2}')
 SNO=$(hl-smi -L | grep accel0 -A 15 | grep "Serial Number" | awk -F': ' '{print $2}')
 SPI=$(hl-smi -L | grep accel0 -A 15 | grep SPI | awk -F'-' '{print $3}')
